### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by blood-stone** [janka102/Bullseye#1]
Having the redstone torch able to set different pulse lengths or remain active for a set amount of time would be very handy

**Comment by janka102** [comment]
I finally added a way to have custom activation time (pulse length) in v0.10.0. Should be available here in a couple days https://dev.bukkit.org/projects/bullseye/files

**Comment by janka102** [comment]
I also published the new version as a release on GitHub here https://github.com/janka102/Bullseye/releases
